### ISSUE TITLE
Confusing positioning messages

### ISSUE THREAD

**Issue by mikaelsvensson** [tunnelbanejakten/tunnelbanejakten-web-app#53]
Det går att få både meddelandet "osäker position" och "du befinner dig vid en kontroll". Det är förvirrande.
![241370533_230089572388278_4966957422374464802_n](https://user-images.githubusercontent.com/789455/132132949-e113adeb-0f93-44fe-9fd0-6e292bc2146f.jpg)

**Comment by mikaelsvensson** [comment]
Kan detta bero på att GPS-mottagningen försämrats sedan förra mätningen? Då är det inte otänkbart att listan med aktiva kartnålar behålls samtidigt som varningsmeddelande visas.

**Comment by traed** [comment]
Jag tror det hände när jag stängde browser-appen och öppnade den igen. Så timern för osäker position kanske resettades men den rensade inte meddelandet om kontrollen?
